# Generated by Django 4.1.7 on 2023-03-30 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='car_record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carnum', models.CharField(max_length=32, verbose_name='车牌号')),
                ('intime', models.DateTimeField(verbose_name='入场时间')),
                ('outtime', models.DateTimeField(verbose_name='出场时间')),
                ('paytime', models.DateTimeField(verbose_name='收费时间')),
                ('amount', models.IntegerField(verbose_name='收费金额')),
            ],
        ),
        migrations.CreateModel(
            name='vip_uer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='姓名')),
                ('carnum', models.CharField(max_length=32, unique=True, verbose_name='车牌号')),
                ('phone', models.CharField(max_length=32, verbose_name='手机号')),
                ('begintime', models.DateTimeField()),
                ('endtime', models.DateTimeField()),
            ],
        ),
    ]
