# Generated by Django 4.1.7 on 2023-03-31 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_license_plate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car_record',
            name='amount',
            field=models.IntegerField(blank=True, null=True, verbose_name='收费金额'),
        ),
        migrations.AlterField(
            model_name='car_record',
            name='outtime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='出场时间'),
        ),
        migrations.AlterField(
            model_name='car_record',
            name='paytime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='收费时间'),
        ),
    ]
